C     EASYCP
C     AN EASY CRYSTAL PLASTICITY CODE
C    
C     SUITABLE FOR:
C     ALL ELEMENT TYPES
C     2D OR 3D
C     SMALL OR LARGE DISPLACEMENT
C
C     PREPARED BY:
C     ERALP DEMIR
C     14.11.2023
C     ERALP.DEMIR@ENG.OX.AC.UK
C
C     THIS CODE IS WRITTEN BASED ON FIONN DUNNE'S METHOD
C     WITH AN ADDITIONAL SEMI-IMPLICIT STATE UPDATE RULE BY DEMIR
C
C     PLEASE CITE THE FOLLOWING REFERENCE IN CASE OF 
C     ACADEMIC OR INDUSTRIAL USE.
C
C
C
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     + RPL,DDSDDT,DRPLDE,DRPLDT,
     + STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     + NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     + CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
C
      CHARACTER*80 CMNAME
      INTEGER, INTENT(IN) :: NPROPS,NSTATV,NTENS,NDI,NSHR
      REAL(8), INTENT(INOUT) :: STRESS(NTENS),
     + STATEV(NSTATV), PNEWDT
      REAL(8), INTENT(IN) :: STRAN(NTENS),DSTRAN(NTENS),
     + TIME(2),DTIME,PREDEF(1),DPRED(1),PROPS(NPROPS),
     + COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      REAL(8), INTENT(OUT) :: DDSDDE(NTENS,NTENS),
     + DDSDDT(NTENS),DRPLDE(NTENS)
      INTEGER, INTENT(IN) :: JSTEP(4),KINC,NOEL,NPT
      
C

      REAL(8) :: L(3,3)
      REAL(8) :: SIG(6), DDSIGDDEPS(6,6)
C     DEBUGGER
C     NEED TO USE A SPECIAL ENVIRONMENT FILE      
      INTEGER :: MATID, NLGEOM, NSLIP, KSTEP
      INTEGER :: DEBUG, DEBUGWAIT
C
C     TURN VS DEBUGGER ON/OFF
      DEBUG=0
      DO WHILE (DEBUG.EQ.1)
          DEBUGWAIT = 1
      END DO
C      
C     SET UNASSIGNED OUTPUTS TO ZERO
      DDSDDT=0.
      DRPLDE=0.
      
C     NON-LINEAR GEOMETRY - LARGE DEFORMATIONS
      NLGEOM = JSTEP(3)
C      
C     STEP NUMBER
      KSTEP = JSTEP(1)
C
C     NUMBER OF SLIP SYSTEMS
      NSLIP = INT(PROPS(6))
C
C
C     INITIALIZATIONS (ONE TIME FOR EVERY SET!)
      IF ((KINC.LE.1).AND.(KSTEP.EQ.1)) THEN
C     
C         IF NOT DONE ONCE
          IF (STATEV(1).EQ.0) THEN
C
C             ONLY ONE-TIME INITIALIZATION FOR ALL
              IF ((NOEL.EQ.1).AND.(NPT.EQ.1)) THEN
C
C                 PRINT INPUTS TO *.LOG AND *.DAT FILES
                  CALL PRINTINPUTS(NPROPS,PROPS)
C
C                 PRINT STATEV LEGEND TO A FILE 
C                 FILENAME: "STATEV_LEGEND.TXT"
C                 SET SCRATCH DIRECTORY TO WORKING DIRECTORY
                  CALL PRINTOUTPUTS(NSLIP)
C
C                 CHECK OF THE CONSISTENCY OF ENTRIES
C                 WILL GIVE AN ERROR MESSAGE IF ANY INCONSISTENCY NOTED              
C
              END IF
C
C             INITIALZE ONCE FOR EACH SET
              CALL INITIALIZE_ONCE(NPROPS,PROPS,NSTATV,STATEV)
C
          END IF
C
          END IF
C      
C     CALCULATE TOTAL VELOCITY GRADIENT AND TOTAL SPIN
C     DIFFERENLY FOR SMALL AND LARGE STRAIN CASES
      CALL VELOCITYGRADIENT(NLGEOM,NTENS,NDI,NSHR,
     + DSTRAN,DFGRD0,DFGRD1,DTIME,L)
C
C         
C
C     ****************************************************
C         
C     CALCULATION OF STRESS AND JACOBIAN
      CALL CRYSTALPLASTICITY(NSLIP,DTIME,L,NPROPS,PROPS,
     + NSTATV,STATEV,PNEWDT,SIG,DDSIGDDEPS)
C
C
C     ****************************************************
C
C     ASSIGNMENT OF STRESS BASED ON THE DIMENSION OF THE PROBLEM
C     3D CASE
      IF (NTENS.EQ.6) THEN
C
          STRESS = SIG
          DDSDDE = DDSIGDDEPS
C
C     PLANE STRAIN CASE
      ELSEIF (NTENS.EQ.4) THEN
C
          STRESS=0.
          STRESS=0.
          STRESS(1) = SIG(1)
          STRESS(2) = SIG(2)
          STRESS(3) = SIG(3)
          STRESS(4) = SIG(4)
C
          DDSDDE=0.
          DDSDDE(1,1) = DDSIGDDEPS(1,1)
          DDSDDE(1,2) = DDSIGDDEPS(1,2)
          DDSDDE(1,3) = DDSIGDDEPS(1,3)
          DDSDDE(2,1) = DDSIGDDEPS(2,1)
          DDSDDE(2,2) = DDSIGDDEPS(2,2)
          DDSDDE(2,3) = DDSIGDDEPS(2,3)
          DDSDDE(3,1) = DDSIGDDEPS(3,1)
          DDSDDE(3,2) = DDSIGDDEPS(3,2)
          DDSDDE(3,3) = DDSIGDDEPS(3,3)
          DDSDDE(4,4) = DDSIGDDEPS(4,4)
C
C     PLANE STRESS CASE
      ELSEIF (NTENS.EQ.3) THEN
C
          STRESS=0.
C         CORRECTION
          STRESS(1) = SIG(1)-SIG(3)
          STRESS(2) = SIG(2)-SIG(3)
C
          STRESS(3) = SIG(4)
C
C
          DDSDDE=0.
          DDSDDE(1,1) = DDSIGDDEPS(1,1)
          DDSDDE(1,2) = DDSIGDDEPS(1,2)
          DDSDDE(2,1) = DDSIGDDEPS(2,1)
          DDSDDE(2,2) = DDSIGDDEPS(2,2)
          DDSDDE(3,3) = DDSIGDDEPS(4,4)
C
C
      ENDIF      
C
C
C
      RETURN
      END SUBROUTINE UMAT
C
C
C     INCLUDE THE SUBROUTINES
      INCLUDE 'defaultinputs.f'
      INCLUDE 'utilities.f'
      INCLUDE 'errors.f'
      INCLUDE 'checks.f'
      INCLUDE 'transformations.f'
      INCLUDE 'initializations.f'
      INCLUDE 'slipvectors.f'
      INCLUDE 'sliplaws.f'
      INCLUDE 'hardeninglaws.f'
      INCLUDE 'singlecrystal.f'
C
C