C     EASYCP
C     AN EASY CRYSTAL PLASTICITY CODE FOR DEVELOPMENT
C
C     ERALP DEMIR
C     14.11.2023
C     ERALP.DEMIR@ENG.OX.AC.UK
C
C
C     SLIP RATE LAWS
C     POWER LAW SLIP
      SUBROUTINE POWERLAW(NSLIP,TAU,TAUC,N,GDOT0,
     + GDOT,DGDOTDTAU)
      IMPLICIT NONE
C     INPUTS
      INTEGER, INTENT(IN) :: NSLIP
      REAL(8), DIMENSION(NSLIP), INTENT(IN) :: TAU
      REAL(8), DIMENSION(NSLIP), INTENT(IN) :: TAUC
      REAL(8), INTENT(IN) :: N
      REAL(8), INTENT(IN) :: GDOT0
C     OUTPUTS
      REAL(8), DIMENSION(NSLIP), INTENT(OUT) :: GDOT
      REAL(8), DIMENSION(NSLIP), INTENT(OUT) :: DGDOTDTAU
C     VARIALBES USED IN THIS SUBROUTINE
      REAL(8) :: X
      INTEGER :: IS
C      
      DO IS=1,NSLIP
C
C
          X = ABS(TAU(IS)) / TAUC(IS)
C
C         SLIP RATE LAW
C         THIS NEEDS TO BE MODIFIED IF A DIFFERENT SLIP LAW NEEDED!
          GDOT(IS) = GDOT0 * X**N * SIGN(1.,TAU(IS))
C
C
C         DERIVATIVE OF SLIP RATE WITH RESPECT TO RSS
C         THIS NEEDS TO BE MODIFIED IF A DIFFERENT SLIP LAW NEEDED!          
          DGDOTDTAU(IS) = GDOT0 * N / TAUC(IS) * X**(N-1.)
C
C
      END DO
C
C
      RETURN
      END SUBROUTINE POWERLAW
C
C
