C     EASYCP
C     AN EASY CRYSTAL PLASTICITY CODE FOR DEVELOPMENT
C
C     ERALP DEMIR
C     14.11.2023
C     ERALP.DEMIR@ENG.OX.AC.UK
C
C
C     CALCULATE DEFAULT VALUES FOR THE PARAMETERS
C     THIS IS DONE TO KEEP ALL THE PARAMETERS IN ONE PLACE!
      SUBROUTINE DEFAULTPARAMETERS(IITERMAX,OITERMAX,ITOL,OTOL,
     + CRIT,CUTBACK)
      INTEGER, INTENT(INOUT) :: IITERMAX
      INTEGER, INTENT(INOUT) :: OITERMAX
      REAL(8), INTENT(INOUT) :: ITOL
      REAL(8), INTENT(INOUT) :: OTOL
      REAL(8), INTENT(INOUT) :: CRIT
      REAL(8), INTENT(INOUT) :: CUTBACK
C     PI      :   NUMBER PI
C     IITERMAX :   MAXIMUM NUMBER OF ITERATIONS FOR THE INNER LOOP
C     OITERMAX :   MAXIMUM NUMBER OF ITERATIONS FOR THE OUTER LOOP
C     ITOL    :   TOLERANCE VALUE FOR THE INNER STRESS LOOP (ABSOLUTE)
C     OTOL    :   TOLERANCE VALUE FOR THE OUTER CRSS LOOP (ABSOLUTE)
C     CRIT    :   CRITICAL THRESHOLD FOR STRESS INCREMENT (BASED ON THE REFERENCE BELOW)
C     CUTBACK :   VALUE OF TIME CUT-BACK      
C     https://doi.org/10.1016/0022-5096(92)80003-9
C
C
C
      OITERMAX = 20
      IITERMAX = 200
C
      ITOL = 1.D-8
      OTOL = 1.D-4
C
      CRIT = 2./3.
C
      CUTBACK = 0.5
C     
      RETURN
      END SUBROUTINE DEFAULTPARAMETERS
C
C
C