C     EASYCP
C     AN EASY CRYSTAL PLASTICITY CODE
C    
C     SUITABLE FOR:
C     ALL ELEMENT TYPES
C     2D OR 3D
C     SMALL OR LARGE DISPLACEMENT
C
C     PREPARED BY:
C     ERALP DEMIR
C     14.11.2023
C     ERALP.DEMIR@ENG.OX.AC.UK
C
C     THIS CODE IS WRITTEN BASED ON FIONN DUNNE'S METHOD
C     MAJOR ADDITIONS BY ERALP DEMIR:
C     - GENERALIZED TO 2D PLANE STRESS, 2D PLANE STRESS, AND 3D
C     - GENERALIZED TO SMALL AND LARGE STRAINS
C     - ANY ELEMENT TYPE
C     - NO BUILT-IN FUNCTIONS IS USED (E.G. MATMUL, TRANPOSE, DOT_PRODUCT, ETC.)
C     - SEMI-IMPLICIT STATE UPDATE
C     - ROTATION INCREMENT
C     - STRESS INCREMENT UPPER THRESHOLD
C     - LIMIT ON THE NUMBER OF EQUILIBRIUM ITERATIONS
C
C     PLEASE CITE THE FOLLOWING REFERENCE IN CASE OF 
C     ACADEMIC OR INDUSTRIAL USE.
C
C
C     GLOBAL VARIABLES FOR NUMBER OF ITERATION CYCLES
C     THE ELEMENT NUMBERING SHALL START FROM "1"
      MODULE GLOBALS
      IMPLICIT NONE
C
C     GLOBAL COUNTER FOR THE INCREMENT
      INTEGER, PUBLIC :: KINC_OLD
      DATA KINC_OLD / 0D+0 /
C
C     NUMBER OF CYCLE
      INTEGER, PUBLIC :: NCYCLE
C
C     NUMBER OF MAXIMUM EQUILIBRIUM CYCLES ALLOWED
C     TURN THIS OFF BY SETTING TO A LARGE NUMBER
C     TURNED OFF BY DEFAULT SETTING IT TO 100
      INTEGER, PARAMETER, PUBLIC :: NCLIMIT = 5D+0
C
C     SUB-STEPPING
C     THE NUMBER OF TIME INCREMENTS FOR SUB-TIME STEPPING
      INTEGER, PARAMETER, PUBLIC :: NTIME = 20D+0
c
      SAVE
      END MODULE GLOBALS
C
C
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     + RPL,DDSDDT,DRPLDE,DRPLDT,
     + STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     + NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     + CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
      USE GLOBALS
C
      CHARACTER*80 CMNAME
      INTEGER, INTENT(IN) :: NPROPS,NSTATV,NTENS,NDI,NSHR
      REAL(8), INTENT(INOUT) :: STRESS(NTENS),
     + STATEV(NSTATV), PNEWDT
      REAL(8), INTENT(IN) :: STRAN(NTENS),DSTRAN(NTENS),
     + TIME(2),DTIME,PREDEF(1),DPRED(1),PROPS(NPROPS),
     + COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      REAL(8), INTENT(OUT) :: DDSDDE(NTENS,NTENS),
     + DDSDDT(NTENS),DRPLDE(NTENS)
      INTEGER, INTENT(IN) :: JSTEP(4),KINC,NOEL,NPT      
C
C
      REAL(8) :: L(3,3), CMATS(6,6)
      REAL(8) :: SIG(6), DDSIGDDEPS(6,6)
      REAL(8) :: DTIMESUB, DFGRD1SUB(3,3)
      REAL(8) :: STATEV0(NSTATV), DFGRD0SUB(3,3)
      REAL(8) :: DSTRANSUB(NTENS)
C     DEBUGGER
C     NEED TO USE A SPECIAL ENVIRONMENT FILE      
      INTEGER :: MATID, NLGEOM, NSLIP, KSTEP
      INTEGER :: DEBUG, DEBUGWAIT
      INTEGER :: I
C
C
C     FIRST TIME ENTRY - RESET
      IF (KINC_OLD.LT.KINC) THEN
          KINC_OLD = KINC
          NCYCLE = 0D+0
C     COUNT THE CYCLES
C     ELEMENT NUMBERING SHALL START FROM "1"
      ELSE
          IF (NOEL.EQ.1) THEN
              IF (NPT.EQ.1) NCYCLE=NCYCLE + 1D+0
          END IF
      END IF
C
C     TURN VS DEBUGGER ON/OFF
      DEBUG=0
      DO WHILE (DEBUG.EQ.1)
          DEBUGWAIT = 1
      END DO
C      
C     SET UNASSIGNED OUTPUTS TO ZERO
      DDSDDT=0.
      DRPLDE=0.
      
C     NON-LINEAR GEOMETRY - LARGE DEFORMATIONS
      NLGEOM = JSTEP(3)
C      
C     STEP NUMBER
      KSTEP = JSTEP(1)
C
C     NUMBER OF SLIP SYSTEMS
      NSLIP = INT(PROPS(6))
C
C
C     INITIALIZATIONS (ONE TIME FOR EVERY SET!)
      IF ((KINC.LE.1).AND.(KSTEP.EQ.1)) THEN
C     
C         IF NOT DONE ONCE
          IF (STATEV(1).EQ.0) THEN
C
C             ONLY ONE-TIME INITIALIZATION FOR ALL
              IF ((NOEL.EQ.1).AND.(NPT.EQ.1)) THEN
C
C                 PRINT INPUTS TO *.LOG AND *.DAT FILES
                  CALL PRINTINPUTS(NPROPS,PROPS)
C
C                 PRINT STATEV LEGEND TO A FILE 
C                 FILENAME: "STATEV_LEGEND.TXT"
C                 SET SCRATCH DIRECTORY TO WORKING DIRECTORY
                  CALL PRINTOUTPUTS(NSLIP)
C
C                 CHECK OF THE CONSISTENCY OF ENTRIES
C                 WILL GIVE AN ERROR MESSAGE IF ANY INCONSISTENCY NOTED              
C
              END IF
C
C             INITIALZE ONCE FOR EACH SET
              CALL INITIALIZE_ONCE(NPROPS,PROPS,NSTATV,STATEV)
C
          END IF
C
          END IF
C      
C     CALCULATE TOTAL VELOCITY GRADIENT AND TOTAL SPIN
C     DIFFERENLY FOR SMALL AND LARGE STRAIN CASES
      CALL VELOCITYGRADIENT(NLGEOM,NTENS,NDI,NSHR,
     + DSTRAN,DFGRD0,DFGRD1,DTIME,L)
C
C         
C
C     ****************************************************
C
C     SAVE THE STATE VARIABLES
      STATEV0=STATEV
C
C     ITERATIVE SOLUTION
      CALL CRYSTALPLASTICITY(NSLIP,DTIME,L,NPROPS,PROPS,
     + NSTATV,STATEV,PNEWDT,SIG,DDSIGDDEPS,CMATS)
C
C     CALCULATION OF STRESS AND JACOBIAN
C     THE TIME INCREMENT SHALL BE OTHER THAN THE FIRST
      IF (KINC.GT.1) THEN
C         THE EQUILIBRIUM CYCLE IS SET AT THE GLOBALS
C         BY DEFAULT IT IS SET TO "5" EQUILIBRIUM CYCLES
          IF ((NCYCLE.GE.NCLIMIT).OR.(PNEWDT.LT.1.)) THEN
C
              WRITE(*,*) 'SUBSTEPPING AT INCREMENT', KINC
C             SUB-TIME STEPPING
              DTIMESUB = DTIME / NTIME
              DSTRANSUB = DSTRAN / NTIME
C
              STATEV=STATEV0
C             LOOP FOR SUB-TIME STEPS
              DO I=1,NTIME
C
                  DFGRD1SUB = (DFGRD1-DFGRD0)* I/NTIME + DFGRD0
                  DFGRD0SUB = (DFGRD1-DFGRD0)* (I-1)/NTIME + DFGRD0
C
                  CALL VELOCITYGRADIENT(NLGEOM,NTENS,NDI,NSHR,
     + DSTRANSUB,DFGRD0SUB,DFGRD1SUB,DTIMESUB,L)
C
                  CALL CRYSTALPLASTICITY(NSLIP,DTIMESUB,L,NPROPS,PROPS,
     + NSTATV,STATEV,PNEWDT,SIG,DDSIGDDEPS,CMATS)
C
C                 IF NOT CONVERGED - EXIT THE DO LOOP
                  IF (PNEWDT.LT.1.) THEN
                      EXIT
                      WRITE(*,*) 'SUBSTEPPING 
     + DID NOT WORK AT INCREMENT', KINC
                  END IF
              END DO
C
C           
C
          END IF
      END IF
C
C     ****************************************************
C
C     ASSIGNMENT OF STRESS BASED ON THE DIMENSION OF THE PROBLEM
C     3D CASE
      IF (NTENS.EQ.6) THEN
C
          STRESS = SIG
          DDSDDE = DDSIGDDEPS
C
C     PLANE STRAIN CASE
      ELSEIF (NTENS.EQ.4) THEN
C
          STRESS=0.
          STRESS=0.
          STRESS(1) = SIG(1)
          STRESS(2) = SIG(2)
          STRESS(3) = SIG(3)
          STRESS(4) = SIG(4)
C
          DDSDDE=0.
          DDSDDE(1,1) = DDSIGDDEPS(1,1)
          DDSDDE(1,2) = DDSIGDDEPS(1,2)
          DDSDDE(1,3) = DDSIGDDEPS(1,3)
          DDSDDE(2,1) = DDSIGDDEPS(2,1)
          DDSDDE(2,2) = DDSIGDDEPS(2,2)
          DDSDDE(2,3) = DDSIGDDEPS(2,3)
          DDSDDE(3,1) = DDSIGDDEPS(3,1)
          DDSDDE(3,2) = DDSIGDDEPS(3,2)
          DDSDDE(3,3) = DDSIGDDEPS(3,3)
          DDSDDE(4,4) = DDSIGDDEPS(4,4)
C
C     PLANE STRESS CASE
      ELSEIF (NTENS.EQ.3) THEN
C
C         Corrected stress for plane stress
          STRESS=0.
          STRESS(1) = SIG(1)
     + -CMATS(1,3)*SIG(3)/CMATS(3,3)
     + -CMATS(1,5)*SIG(5)/CMATS(5,5)
     + -CMATS(1,6)*SIG(6)/CMATS(6,6)
C
          STRESS(2) = SIG(2)
     + -CMATS(2,3)*SIG(3)/CMATS(3,3)
     + -CMATS(2,5)*SIG(5)/CMATS(5,5)
     + -CMATS(2,6)*SIG(6)/CMATS(6,6)
C
          STRESS(3) = SIG(4)
     + -CMATS(4,3)*SIG(3)/CMATS(3,3)
     + -CMATS(4,5)*SIG(5)/CMATS(5,5)
     + -CMATS(4,6)*SIG(6)/CMATS(6,6)
C
C         Corrected DDSIGDDEPSan for plane stress
          DDSDDE=0.
          DDSDDE(1,1) = DDSIGDDEPS(1,1) -
     + DDSIGDDEPS(1,3)*DDSIGDDEPS(3,1)/DDSIGDDEPS(3,3)
          DDSDDE(1,2) = DDSIGDDEPS(1,2) -
     + DDSIGDDEPS(1,3)*DDSIGDDEPS(3,2)/DDSIGDDEPS(3,3)
          DDSDDE(1,3) = DDSIGDDEPS(1,4) -
     + DDSIGDDEPS(1,3) * DDSIGDDEPS(3,4) / DDSIGDDEPS(3,3)
          DDSDDE(2,1) = DDSIGDDEPS(2,1) -
     + DDSIGDDEPS(2,3)*DDSIGDDEPS(3,1)/DDSIGDDEPS(3,3)
          DDSDDE(2,2) = DDSIGDDEPS(2,2) -
     + DDSIGDDEPS(2,3)*DDSIGDDEPS(3,2)/DDSIGDDEPS(3,3)
          DDSDDE(2,3) = DDSIGDDEPS(2,4) -
     + DDSIGDDEPS(2,3) * DDSIGDDEPS(3,4) / DDSIGDDEPS(3,3)
          DDSDDE(3,1) = DDSIGDDEPS(4,1) -
     + DDSIGDDEPS(4,3) * DDSIGDDEPS(3,1) / DDSIGDDEPS(3,3)
          DDSDDE(3,2) = DDSIGDDEPS(4,2) -
     + DDSIGDDEPS(4,3) * DDSIGDDEPS(3,2) / DDSIGDDEPS(3,3)
          DDSDDE(3,3) = DDSIGDDEPS(4,4) -
     + DDSIGDDEPS(4,3) * DDSIGDDEPS(3,4) / DDSIGDDEPS(3,3)
C
C
      ENDIF      
C
C
C
      RETURN
      END SUBROUTINE UMAT
C
C
C     INCLUDE THE SUBROUTINES
      INCLUDE 'defaultinputs.f'
      INCLUDE 'utilities.f'
      INCLUDE 'errors.f'
      INCLUDE 'checks.f'
      INCLUDE 'transformations.f'
      INCLUDE 'initializations.f'
      INCLUDE 'slipvectors.f'
      INCLUDE 'sliplaws.f'
      INCLUDE 'hardeninglaws.f'
      INCLUDE 'singlecrystal.f'
C
C